/**
 * Save Component for Filterable Grid Block
 * 
 * This block uses dynamic rendering (PHP), so we return null here.
 * All the HTML output is generated server-side in the render_callback.
 * 
 * @package MyTheme
 */

export default function save() {
    // Return null to use dynamic rendering
    // The block's HTML is generated by the PHP render_callback
    return null;
}