import { useBlockProps, InnerBlocks } from '@wordpress/block-editor';

export default function save({ attributes }) {
    const { contentBackgroundColor } = attributes;

    const blockProps = useBlockProps.save({
        className: 'wagepoint-tabs',
        'data-tabs': true,
    });

    return (
        <div {...blockProps}>
            <div className="wagepoint-tabs__container">
                {/* Tab Navigation - will be generated by frontend.js */}
                <div className="wagepoint-tabs__nav" role="tablist">
                    {/* Tabs will be dynamically created from Panel blocks */}
                </div>

                {/* Panels Container - use bg- prefix instead of has- */}
                <div className={`wagepoint-tabs__panels-container bg-${contentBackgroundColor}`}>
                    <InnerBlocks.Content />
                </div>
            </div>
        </div>
    );
}